name: DTrade
main: org.dtrade.DTrade
version: 1.0.0
api-version: 1.18
depend: ["Vault"]

commands:
  trade:
    usage: /trade [player name]
    description: sends a trade request to a player
  tradelog:
    permission: dtrade.tradelog
    usage: /tradelog [player name]
    description: Views the trade logs of a player

permissions:
  dtrade.tradelog:
    description: Allows viewing a players trade logs
    default: op